services:
  rundeck:
    build:
      context: ./rundeck
      cache_from:
        - ${RUNDECK_IMAGE_NAME}:cache-buildx
      cache_to:
        - mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${RUNDECK_IMAGE_NAME}:cache-buildx
      args:
        BUILDKIT_INLINE_CACHE: 1
        RUNDECK_VERSION: ${RUNDECK_VERSION:-5.12.0-20250512}
    image: ${RUNDECK_IMAGE_NAME}:${BITBUCKET_BUILD_NUMBER}-buildx
    x-bake:
      # buildx bake 固有の設定
      push: true
  nginx:
    build:
      context: ./nginx
      cache_from:
        - ${NGINX_IMAGE_NAME}:cache-buildx
      cache_to:
        - mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${NGINX_IMAGE_NAME}:cache-buildx
      args:
        BUILDKIT_INLINE_CACHE: 1
        NGINX_VERSION: ${NGINX_VERSION:-1.28.0}
    image: ${NGINX_IMAGE_NAME}:${BITBUCKET_BUILD_NUMBER}-buildx
    x-bake:
      # buildx bake 固有の設定
      push: true
  oauth2-proxy:
    build:
      context: ./oauth2-proxy
      cache_from:
        - ${OAUTH2_PROXY_IMAGE_NAME}:cache-buildx
      cache_to:
        - mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${OAUTH2_PROXY_IMAGE_NAME}:cache-buildx
      args:
        BUILDKIT_INLINE_CACHE: 1
        OAUTH2_PROXY_VERSION: ${OAUTH2_PROXY_VERSION:-v7.4.0}
    image: ${OAUTH2_PROXY_IMAGE_NAME}:${BITBUCKET_BUILD_NUMBER}-buildx
    x-bake:
      # buildx bake 固有の設定
      push: true
