services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - oauth2-proxy
    networks:
      - rundeck-network
    restart: unless-stopped

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    container_name: oauth2-proxy
    command:
      - --provider=oidc
      - --oidc-issuer-url=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
      - --client-id=${COGNITO_CLIENT_ID}
      - --client-secret=${COGNITO_CLIENT_SECRET}
      - --email-domain=*
      - --http-address=0.0.0.0:4180
      - --redirect-url=http://localhost/oauth2/callback
      - --cookie-domain=localhost
      - --cookie-secure=false
      - --set-xauthrequest=true
      - --set-authorization-header=true
      - --pass-user-headers=true
      - --pass-access-token=true
      - --pass-authorization-header=true
      - --scope=openid email profile
      - --oidc-email-claim=email
      - --oidc-groups-claim=cognito:groups
      - --skip-provider-button=true
      - --reverse-proxy=true
      - --set-basic-auth=false
      - --prefer-email-to-user=true
      - --pass-host-header=true
      - --cookie-expire=24h
      - --cookie-refresh=1h
      - --upstream=static://202
      - --set-xauthrequest=true
      - --session-store-type=cookie
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
    ports:
      - "4180:4180"
    depends_on:
      - rundeck
    networks:
      - rundeck-network
    restart: unless-stopped

  rundeck:
    image: rundeck/rundeck:5.12.0-20250512
    container_name: rundeck-server
    environment:
      - RUNDECK_GRAILS_URL=http://localhost
      - RUNDECK_GUI_TITLE=Rundeck with OAuth2
      - RUNDECK_GUI_BRAND=OAuth2 Rundeck
      - RUNDECK_PREAUTH_ENABLED=true
      - RUNDECK_PREAUTH_ATTRIBUTE_NAME=REMOTE_USER_GROUPS
      - RUNDECK_PREAUTH_DELIMITER=,
      - RUNDECK_PREAUTH_USERNAME_HEADER=X-Forwarded-User
      - RUNDECK_PREAUTH_ROLES_HEADER=X-Forwarded-Roles
      - RUNDECK_PREAUTH_REDIRECT_LOGOUT=false
      - RUNDECK_PREAUTH_REDIRECT_URL=
      - RUNDECK_PREAUTH_USERSYNC_ENABLED=true
      - RUNDECK_ACL_DIR=/home/rundeck/server/config/acl
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_ENABLED=true
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_DEFAULTROLES=admin,user,architect,deploy,build
      - RUNDECK_SECURITY_AUTHORIZATION_FORM_ENABLED=false
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_USERNAMEHEADER=X-Forwarded-User
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_ROLESHEADER=X-Forwarded-Roles
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_ATTRIBUTENAME=REMOTE_USER_GROUPS
      - RUNDECK_SECURITY_AUTHORIZATION_PREAUTHENTICATED_DELIMITER=,
    volumes:
      - rundeck-data:/home/rundeck/server/data
      - rundeck-logs:/home/rundeck/var/logs
      - rundeck-plugins:/home/rundeck/libext
      - ./rundeck/realm.properties:/home/rundeck/server/config/realm.properties
      - ./rundeck/acl:/home/rundeck/server/config/acl
    ports:
      - "4440:4440"
    networks:
      - rundeck-network
    restart: unless-stopped

volumes:
  rundeck-data:
    driver: local
  rundeck-projects:
    driver: local
  rundeck-logs:
    driver: local
  rundeck-plugins:
    driver: local

networks:
  rundeck-network:
    driver: bridge 